import { DOCUMENT } from '@angular/common';
import { Inject, Injectable } from '@angular/core';
import { Meta, Title } from '@angular/platform-browser';
import { NavigationEnd, NavigationStart, Router } from '@angular/router';

export interface SeoData {
  title: string;
  description: string;
  robots?: string;
  image?: string;
  imageAlt?: string;
}

export interface DynamicSeoData extends SeoData {
  canonicalPath: string;
  jsonLd?: Record<string, unknown>;
}

/** Product SEO payload generated by platform seo-engine */
export interface ProductSeoPayload {
  slug?: string;
  metaTitle?: string;
  metaDescription?: string;
  canonical?: string;
  altTexts?: { primary?: string };
  openGraph?: { title?: string; description?: string; image?: string | null };
  jsonLd?: Record<string, unknown>;
}

@Injectable({ providedIn: 'root' })
export class SeoService {
  private readonly siteUrl = 'https://gallery-mazhari.ir';
  private readonly defaultImage = `${this.siteUrl}/assets/images/home-hero-bride.webp`;
  private readonly jsonLdId = 'mazhari-route-jsonld';

  constructor(
    private readonly router: Router,
    private readonly title: Title,
    private readonly meta: Meta,
    @Inject(DOCUMENT) private readonly document: Document
  ) {}

  init(): void {
    this.router.events.subscribe(event => {
      if (event instanceof NavigationStart) {
        this.clearJsonLd();
      }
      if (event instanceof NavigationEnd) {
        this.updateFromRoute();
      }
    });

    this.updateFromRoute();
  }

  /** Apply route/entity-derived metadata without allowing route fallback data to overwrite it. */
  applyDynamicSeo(seo: DynamicSeoData): void {
    const canonical = this.canonicalUrl(seo.canonicalPath);
    const image = this.absoluteAssetUrl(seo.image);
    const robots = seo.robots ?? 'index,follow,max-image-preview:large';

    this.title.setTitle(seo.title);
    this.meta.updateTag({ name: 'description', content: seo.description });
    this.meta.updateTag({ name: 'robots', content: robots });
    this.meta.updateTag({ property: 'og:title', content: seo.title });
    this.meta.updateTag({ property: 'og:description', content: seo.description });
    this.meta.updateTag({ property: 'og:url', content: canonical });
    this.meta.updateTag({ property: 'og:image', content: image });
    this.meta.updateTag({ property: 'og:image:alt', content: seo.imageAlt ?? 'گالری مظهری' });
    this.meta.updateTag({ name: 'twitter:card', content: 'summary_large_image' });
    this.meta.updateTag({ name: 'twitter:title', content: seo.title });
    this.meta.updateTag({ name: 'twitter:description', content: seo.description });
    this.meta.updateTag({ name: 'twitter:image', content: image });
    this.setCanonical(canonical);

    if (seo.jsonLd) {
      this.setJsonLd(seo.jsonLd);
    } else {
      this.clearJsonLd();
    }
  }

  /** Apply collection/category metadata and structured data from the resolved route entity. */
  applyCollectionSeo(seo: Omit<DynamicSeoData, 'jsonLd'>): void {
    const canonical = this.canonicalUrl(seo.canonicalPath);
    this.applyDynamicSeo({
      ...seo,
      jsonLd: {
        '@context': 'https://schema.org',
        '@type': 'CollectionPage',
        name: seo.title,
        description: seo.description,
        url: canonical
      }
    });
  }

  /** Apply auto-generated product SEO (title, OG, canonical, JSON-LD). */
  applyProductSeo(seo: ProductSeoPayload | null | undefined, fallbackName?: string): void {
    if (!seo) return;
    const title =
      seo.metaTitle ||
      (fallbackName ? `${fallbackName} | گالری مظهری` : 'گالری مظهری');
    const description =
      seo.metaDescription || 'گالری مظهری — لباس عروس و اکسسوری عروس';
    const canonicalPath = seo.canonical || this.currentPath();

    this.applyDynamicSeo({
      title,
      description,
      canonicalPath,
      image: seo.openGraph?.image || undefined,
      imageAlt: seo.altTexts?.primary || 'گالری مظهری',
      jsonLd: seo.jsonLd
    });

    this.meta.updateTag({ property: 'og:title', content: seo.openGraph?.title || title });
    this.meta.updateTag({
      property: 'og:description',
      content: seo.openGraph?.description || description
    });
  }

  private updateFromRoute(): void {
    const path = this.currentPath();
    if (this.isDynamicEntityPath(path)) return;

    let route = this.router.routerState.snapshot.root;
    while (route.firstChild) route = route.firstChild;

    const seo = route.data['seo'] as SeoData | undefined;
    if (!seo) return;

    const canonicalUrl = this.canonicalUrl(path);
    const image = this.absoluteAssetUrl(seo.image);
    const robots = this.router.url.includes('?s=')
      ? 'noindex,follow'
      : (seo.robots ?? 'index,follow,max-image-preview:large');

    this.clearJsonLd();
    this.title.setTitle(seo.title);
    this.meta.updateTag({ name: 'description', content: seo.description });
    this.meta.updateTag({ name: 'robots', content: robots });
    this.meta.updateTag({ property: 'og:title', content: seo.title });
    this.meta.updateTag({ property: 'og:description', content: seo.description });
    this.meta.updateTag({ property: 'og:url', content: canonicalUrl });
    this.meta.updateTag({ property: 'og:image', content: image });
    this.meta.updateTag({
      property: 'og:image:alt',
      content: seo.imageAlt ?? 'گالری مظهری'
    });
    this.meta.updateTag({ name: 'twitter:card', content: 'summary_large_image' });
    this.meta.updateTag({ name: 'twitter:title', content: seo.title });
    this.meta.updateTag({ name: 'twitter:description', content: seo.description });
    this.meta.updateTag({ name: 'twitter:image', content: image });
    this.setCanonical(canonicalUrl);
  }

  private currentPath(): string {
    return this.router.url.split(/[?#]/, 1)[0] || '/';
  }

  private isDynamicEntityPath(path: string): boolean {
    return path.startsWith('/product/') || path.startsWith('/shop/') || path.startsWith('/collections/');
  }

  private canonicalUrl(value: string): string {
    const raw = value.split(/[?#]/, 1)[0] || '/';
    if (raw === this.siteUrl || raw.startsWith(`${this.siteUrl}/`)) {
      return raw;
    }
    const path = raw.startsWith('/') ? raw : `/${raw}`;
    return `${this.siteUrl}${path}`;
  }

  private absoluteAssetUrl(image?: string): string {
    if (!image) return this.defaultImage;
    if (/^https?:\/\//i.test(image)) return image;
    return `${this.siteUrl}${image.startsWith('/') ? image : `/${image}`}`;
  }

  private setCanonical(url: string): void {
    let canonical = this.document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]');
    if (!canonical) {
      canonical = this.document.createElement('link');
      canonical.rel = 'canonical';
      this.document.head.appendChild(canonical);
    }
    canonical.href = url;
  }

  private setJsonLd(data: Record<string, unknown>): void {
    let script = this.document.getElementById(this.jsonLdId) as HTMLScriptElement | null;
    if (!script) {
      script = this.document.createElement('script');
      script.type = 'application/ld+json';
      script.id = this.jsonLdId;
      this.document.head.appendChild(script);
    }
    script.textContent = JSON.stringify(data);
  }

  private clearJsonLd(): void {
    this.document.getElementById(this.jsonLdId)?.remove();
    // Remove the legacy product-only node when navigating from builds before RM-12 governance.
    this.document.getElementById('mazhari-product-jsonld')?.remove();
  }
}
