
import { Inject, Injectable, DOCUMENT } from '@angular/core';
import { Meta, Title } from '@angular/platform-browser';
import { NavigationEnd, Router } from '@angular/router';
import { filter } from 'rxjs';

export interface SeoData {
  title: string;
  description: string;
  robots?: string;
  image?: string;
  imageAlt?: string;
}

/** Product SEO payload generated by platform seo-engine */
export interface ProductSeoPayload {
  slug?: string;
  metaTitle?: string;
  metaDescription?: string;
  canonical?: string;
  altTexts?: { primary?: string };
  openGraph?: { title?: string; description?: string; image?: string | null };
  jsonLd?: Record<string, unknown>;
}

@Injectable({ providedIn: 'root' })
export class SeoService {
  private readonly siteUrl = 'https://gallery-mazhari.ir';
  private readonly defaultImage = `${this.siteUrl}/assets/images/home-hero-bride.webp`;

  constructor(
    private readonly router: Router,
    private readonly title: Title,
    private readonly meta: Meta,
    @Inject(DOCUMENT) private readonly document: Document
  ) {}

  init(): void {
    this.router.events
      .pipe(filter((event): event is NavigationEnd => event instanceof NavigationEnd))
      .subscribe(() => this.updateFromRoute());

    this.updateFromRoute();
  }

  /** Apply auto-generated product SEO (title, OG, canonical, JSON-LD). */
  applyProductSeo(seo: ProductSeoPayload | null | undefined, fallbackName?: string): void {
    if (!seo) return;
    const title =
      seo.metaTitle ||
      (fallbackName ? `${fallbackName} | گالری مظهری` : 'گالری مظهری');
    const description =
      seo.metaDescription || 'گالری مظهری — لباس عروس و اکسسوری عروس';
    const canonical =
      seo.canonical ||
      `${this.siteUrl}${this.router.url.split(/[?#]/, 1)[0] || '/'}`;
    const image = seo.openGraph?.image || this.defaultImage;
    const imageAlt = seo.altTexts?.primary || 'گالری مظهری';

    this.title.setTitle(title);
    this.meta.updateTag({ name: 'description', content: description });
    this.meta.updateTag({ name: 'robots', content: 'index,follow,max-image-preview:large' });
    this.meta.updateTag({ property: 'og:title', content: seo.openGraph?.title || title });
    this.meta.updateTag({
      property: 'og:description',
      content: seo.openGraph?.description || description
    });
    this.meta.updateTag({ property: 'og:url', content: canonical });
    this.meta.updateTag({ property: 'og:image', content: image });
    this.meta.updateTag({ property: 'og:image:alt', content: imageAlt });
    this.meta.updateTag({ name: 'twitter:card', content: 'summary_large_image' });
    this.meta.updateTag({ name: 'twitter:title', content: title });
    this.meta.updateTag({ name: 'twitter:description', content: description });
    this.meta.updateTag({ name: 'twitter:image', content: image });
    this.setCanonical(canonical);
    if (seo.jsonLd) this.setJsonLd(seo.jsonLd);
  }

  private updateFromRoute(): void {
    let route = this.router.routerState.snapshot.root;
    while (route.firstChild) route = route.firstChild;

    const seo = route.data['seo'] as SeoData | undefined;
    if (!seo) return;

    const path = this.router.url.split(/[?#]/, 1)[0] || '/';
    const canonicalUrl = `${this.siteUrl}${path === '/' ? '/' : path}`;
    const image = seo.image ? `${this.siteUrl}${seo.image}` : this.defaultImage;
    const robots = this.router.url.includes('?s=')
      ? 'noindex,follow'
      : (seo.robots ?? 'index,follow,max-image-preview:large');

    this.title.setTitle(seo.title);
    this.meta.updateTag({ name: 'description', content: seo.description });
    this.meta.updateTag({ name: 'robots', content: robots });
    this.meta.updateTag({ property: 'og:title', content: seo.title });
    this.meta.updateTag({ property: 'og:description', content: seo.description });
    this.meta.updateTag({ property: 'og:url', content: canonicalUrl });
    this.meta.updateTag({ property: 'og:image', content: image });
    this.meta.updateTag({
      property: 'og:image:alt',
      content: seo.imageAlt ?? 'گالری مظهری'
    });
    this.meta.updateTag({ name: 'twitter:title', content: seo.title });
    this.meta.updateTag({ name: 'twitter:description', content: seo.description });
    this.meta.updateTag({ name: 'twitter:image', content: image });
    this.setCanonical(canonicalUrl);
  }

  private setCanonical(url: string): void {
    let canonical = this.document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]');
    if (!canonical) {
      canonical = this.document.createElement('link');
      canonical.rel = 'canonical';
      this.document.head.appendChild(canonical);
    }
    canonical.href = url;
  }

  private setJsonLd(data: Record<string, unknown>): void {
    const id = 'mazhari-product-jsonld';
    let script = this.document.getElementById(id) as HTMLScriptElement | null;
    if (!script) {
      script = this.document.createElement('script');
      script.type = 'application/ld+json';
      script.id = id;
      this.document.head.appendChild(script);
    }
    script.textContent = JSON.stringify(data);
  }
}
