import { Directive, ElementRef, Input, OnChanges, Renderer2, inject } from '@angular/core';

/** Connects product originals to the WebP derivatives generated by the API. */
@Directive({ selector: 'img[appResponsiveProductImage]', standalone: true })
export class ResponsiveProductImageDirective implements OnChanges {
  @Input() appResponsiveProductImage = '';
  @Input() responsiveSizes = '(max-width: 640px) 50vw, (max-width: 1200px) 33vw, 320px';
  private readonly element = inject(ElementRef<HTMLImageElement>);
  private readonly renderer = inject(Renderer2);

  ngOnChanges(): void {
    const srcset = this.createSrcset(this.appResponsiveProductImage);
    if (srcset) {
      this.renderer.setAttribute(this.element.nativeElement, 'srcset', srcset);
      this.renderer.setAttribute(this.element.nativeElement, 'sizes', this.responsiveSizes);
    } else {
      this.renderer.removeAttribute(this.element.nativeElement, 'srcset');
      this.renderer.removeAttribute(this.element.nativeElement, 'sizes');
    }
    this.renderer.setAttribute(this.element.nativeElement, 'decoding', 'async');
  }

  private createSrcset(url: string): string | null {
    const cleanUrl = url?.split(/[?#]/, 1)[0];
    const match = cleanUrl?.match(/^(.*\/uploads\/products)\/([^/]+)\.[^./]+$/i);
    if (!match) return null;
    const base = `${match[1]}/_derivatives/${match[2]}`;
    return [`${base}-thumb.webp 320w`, `${base}-medium.webp 800w`, `${base}-large.webp 1600w`, `${base}-retina.webp 2400w`].join(', ');
  }
}
